# Automatically generated by configure - do not modify

all:
SRC_PATH=/home/sangyun/ConfFDP
TARGET_DIRS=x86_64-softmmu
GDB=/usr/bin/gdb
SUBDIRS= contrib/plugins
PYTHON=/home/sangyun/ConfFDP/femu-scripts/pyvenv/bin/python3 -B
MKVENV_ENSUREGROUP=/home/sangyun/ConfFDP/femu-scripts/pyvenv/bin/python3 -B /home/sangyun/ConfFDP/python/scripts/mkvenv.py ensuregroup  --online
GENISOIMAGE=/usr/bin/genisoimage
MESON=/home/sangyun/ConfFDP/femu-scripts/pyvenv/bin/meson
NINJA=/usr/local/bin/ninja
EXESUF=
TCG_TESTS_TARGETS= x86_64-softmmu
