# Automatically generated by configure - do not modify
TARGET_NAME=x86_64
TARGET=x86_64-softmmu
EXTRA_CFLAGS=-m64
CC=cc
CCAS=cc
AR=ar
AS=as
LD=ld
NM=nm
OBJCOPY=objcopy
RANLIB=ranlib
STRIP=strip
BUILD_STATIC=
QEMU=/home/sangyun/ConfFDP/femu-scripts/qemu-system-x86_64
GDB=/usr/bin/gdb
